app/modules/user/views.py
from app import db
from app.helpers.decorators import login_required
from app.models import User
from app.models.user_dict import UserDict
from app.modules.user.forms import ChangePasswordForm, LoginForm, RegisterForm
from flask import (Blueprint, flash, g, redirect, render_template, request,
                   session, url_for)

module = Blueprint('user', __name__, url_prefix='/user')


@module.route('/', methods=['GET'])
def index():
    return redirect(url_for('user.dashboard'))


@module.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm(request.form)
    if request.method == 'POST' and form.validate():
        user = User.query.filter(User.username == form.username.data).first()

        if user and user.check_password(form.password.data):
            session['user_id'] = user.id
            flash("You have logged successfully", 'success')
            return redirect(url_for('user.dashboard'))

        flash("Username or password is incorrect", 'error')
    return render_template('user/login.html', form=form)


@module.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm(request.form)
    if request.method == 'POST' and form.validate():
        user = User.query.filter(User.username == form.username.data).first()

        if user:
            flash("Username is already taken", 'error')
            return render_template('user/register.html', form=form)

        user = User(username=form.username.data)
        user.set_password(form.password.data)
        db.session.add(user)
        db.session.commit()
        flash("You have been successfully registered", 'success')
        return redirect(url_for('user.login'))

    return render_template('user/register.html', form=form)


@module.route('/logout', methods=['GET'])
@login_required
def logout():
    session.pop('user_id', None)
    flash('You have been logged out', 'success')
    return redirect(url_for('user.login'))


@module.route('/change-password', methods=['GET', 'POST'])
@login_required
def change_password():
    form = ChangePasswordForm(request.form)
    if request.method == 'POST' and form.validate():
        user = User.query.filter(User.username == g.user.username).first()

        if not user.check_password(form.password.data):
            flash("Please type last password correctly.")
            return render_template('user/change_password.html', form=form)

        user.set_password(form.new_password.data)
        db.session.commit()
        flash('Your password changed successfully')
        return redirect(url_for('user.dashboard'))

    return render_template('user/change_password.html', form=form)


@module.route('/dashboard', methods=['GET'])
@login_required
def dashboard():
    context = dict()
    context['words'] = UserDict.query.filter_by(user_id=g.user.id)
    return render_template('user/dashboard.html', content=context)

app/modules/word/views.py
import json
import random

import requests
from app import db
from app.helpers.decorators import login_required
from app.models import Synonym, UserDict, Word
from app.models.definition import Definition
from app.models.user import User
from flask import (Blueprint, g, redirect, render_template,
                   request, url_for)
from sqlalchemy.sql.expression import func
from config import configuration


module = Blueprint('word', __name__, url_prefix='/word')


@module.route('/search', methods=['GET', 'POST'])
@login_required
def search():
    context = dict()
    query = (request.args.get('search')).rstrip()
    user = g.user
    word = Word.query.filter_by(title=query).first()
    context['definitions'] = []

    if word:

        if not (user.words.filter_by(id=word.id).first()):
            user.words.append(word)
            db.session.add(user)
            db.session.commit()

        if not user.can_practice:
            if (user.words.count()) >= 10:
                user.can_practice = True

        context['definitions'] = Definition.query.filter_by(
            word_id=word.id
            ).all()
        user_dict = UserDict.query.filter_by(
            user_id=user.id,
            word_id=word.id).first()

        if not user_dict:
            user_dict = UserDict(
                user_id=user.id,
                word_id=word.id,
                search_count=1
            )
        else:
            user_dict.search_count += 1

        db.session.add(user_dict)
        db.session.commit()

    else:
        response = requests.request(
            'GET',
            f"{configuration.URL}{query}",
            headers=configuration.HEADERS
        )

        if response.status_code != 200:
            return render_template('user/index.html', content=context)

        items = json.loads(response.content)
        if response.status_code == 200 and items['results']:
            word = Word(title=query)
            db.session.add(word)
            db.session.commit()
            user.words.append(word)
            if not user.can_practice:
                if (user.words.count()) >= 10:
                    user.can_practice = True
            for item in items['results']:
                definition = Definition(
                    content=item['definition'],
                    word_id=word.id,
                    part_of_speech=item.get('partOfSpeech')
                )
                db.session.add(definition)
                db.session.commit()
                if item.get('synonyms'):
                    for synonym in item.get('synonyms'):
                        synonym = Synonym(title=synonym)
                        db.session.add(synonym)
                        definition.synonyms.append(synonym)

                db.session.add(user)
                db.session.add(definition)
                db.session.commit()
            user_dict = UserDict(
                user_id=user.id,
                word_id=word.id,
                search_count=1
            )

            db.session.add(user_dict)
            db.session.commit()

            context['definitions'] = Definition.query.filter_by(
                word_id=word.id
                ).all()

    return render_template('user/index.html', content=context)


@module.route('/details/<id>', methods=['GET'])
@login_required
def details(id):
    context = dict()
    word = Word.query.get(id)
    print(word)
    context['word'] = word
    return render_template('user/details.html', content=context)


@module.route('/practice', methods=['GET', 'POST'])
@login_required
def practice():
    context = dict()
    return render_template('user/practice.html', content=context)


@module.route('/practicing', methods=['GET'])
@login_required
def practicing():
    context = dict()
    user = User.query.get(g.user.id)
    three_words = user.words.order_by(func.random()).limit(3).all()
    querying_word = random.choice(three_words)
    user_dict = UserDict.query.filter_by(
        user_id=g.user.id,
        word_id=querying_word.id
        ).first()
    user_dict.appearance_count_update()
    querying_definition = Definition.query.filter_by(
        word_id=querying_word.id
        ).order_by(func.random()).first()

    context = json.dumps({
        'querying_definition': querying_definition.content,
        'first_word': three_words[0].title,
        'second_word': three_words[1].title,
        'third_word': three_words[2].title,
        })
    return context


@module.route('/check', methods=['POST'])
@login_required
def check():
    context = dict()
    if request.method == 'POST':
        querying_definition = request.form.get('querying_definition')
        answer = request.form.get('answer')

        definition_obj = Definition.query.filter_by(
            content=querying_definition
            ).first()
        exact_word = Word.query.get(definition_obj.word_id)
        user_dict_answer = UserDict.query.filter_by(
            user_id=g.user.id,
            word_id=exact_word.id
            ).first()
        user_dict_exact_answer = UserDict.query.filter_by(
            user_id=g.user.id,
            word_id=exact_word.id
            ).first()

        if exact_word.title == answer:
            user_dict_answer.practice_point += 1
            db.session.add(user_dict_answer)
            db.session.commit()

            context = json.dumps({
                'result': 'Contragulations. Your answer is correct',
                'definition': querying_definition,
                'word': exact_word.title,
            })
            return context

        else:
            words = request.form.getlist('words[]')
            words.remove(exact_word.title)
            user_dict_exact_answer.practice_point -= 2
            db.session.add(user_dict_exact_answer)
            db.session.commit()

            for item in words:
                word = Word.query.filter_by(title=item).first()
                user_dict_other = UserDict.query.filter_by(
                    user_id=g.user.id,
                    word_id=word.id
                ).first()
                user_dict_other.practice_point -= 1
                db.session.add(user_dict_other)
                db.session.commit()

            context = json.dumps({
                'result': 'Opps. Your answer is incorrect',
                'definition': querying_definition,
                'word': exact_word.title,
            })
            return context


@module.route('/exit-practice', methods=['GET'])
@login_required
def exit_practice():
    return redirect(url_for('word.practice'))

app/templates/base/components/footer.html
<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
        <div class="col-12 col-md">
            <small class="d-block mb-3 text-muted">© 2021</small>
        </div>
        <div class="row">
            <h5 class="text-center">Personal Dictionary and Memorizing App</h5>

        </div>
       
    </div>

</footer>

app/templates/base/components/footer_scripts.html
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

app/templates/base/components/head.html
<title></title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

app/templates/base/components/messages.html
{% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
    <ul class=flashes>
    {% for category, message in messages %}
      <li class="{{ category }}">{{ message }}</li>
    {% endfor %}
    </ul>
  {% endif %}
{% endwith %}

app/templates/base/components/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{{ url_for('user.dashboard') }}">Dictionary App</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        {% if g.user %}
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('user.dashboard') }}">Dashboard</a>
        </li>
        {% if g.user.can_practice %}

        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('word.practice') }}">Practice</a>
        </li>
        {% endif %}
        {% endif %}
      </ul>
      {% if g.user %}
      <form class="d-flex mx-auto" action="{{ url_for('word.search') }}">
        <input class="form-control me-2" name="search" type="text" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
      {% endif %}

      <ul class="navbar-nav ml-auto mb-2 mb-lg-0">
        {% if g.user %}
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('user.logout') }}">Logout({{g.user.username}})</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('user.change_password')}}">Change Password</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('user.login') }}">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('user.register') }}">Register</a>
        </li>
        {% endif %}


      </ul>

    </div>
  </div>
</nav>

app/templates/base/components/result_table.html
<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Definition</th>
            <th scope="col">Part of Speech</th>
            <th scope="col">Synonyms</th>
        </tr>
    </thead>
    <tbody>
        {% if content.definitions %}
        {% for definition in content.definitions %}
        <tr>
            <th class="col-1" scope="row">{{loop.index}}</th>
            <td class="col-6">{{definition.content}}</td>
            <td class="col-2">{{definition.part_of_speech}}</td>
            <td class="col-3">
                {% for i in definition.synonyms %}
                *{{i.title}} <br>
                {% endfor %}
            </td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <h2 class="text-center">
                The word you were looking for was not found.
            </h2>
        </tr>
        {% endif %}
    </tbody>
</table>