app/models/user.py
from app import db
from app.models.default import Base
from werkzeug.security import check_password_hash, generate_password_hash

words = db.Table('user_words', db.Column(
        'word_id',
        db.Integer,
        db.ForeignKey('word.id'),
        primary_key=True),
    db.Column(
        'user_id',
        db.Integer,
        db.ForeignKey('user.id'),
        primary_key=True)
)


class User(Base):
    username = db.Column(
        db.String(150),
        nullable=False
    )
    password = db.Column(
        db.String(150),
        nullable=False
    )
    words = db.relationship(
        'Word',
        secondary=words,
        lazy='dynamic',
        backref=db.backref(
            'users',
            lazy=True,
            uselist=False)
    )
    can_practice = db.Column(
        db.Boolean,
        default=False
    )
    user_dict = db.relationship(
        'UserDict',
        backref="User",
        lazy=True
    )

    def set_password(self, password):
        self.password = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password, password)

    def __repr__(self):
        return '<User %r>' % self.username

app/modules/user/forms.py
from flask_wtf import FlaskForm
from wtforms import PasswordField, StringField, SubmitField
from wtforms.validators import DataRequired


class RegisterForm(FlaskForm):
    username = StringField(
        'Username',
        [DataRequired("Username field cannot be empty")]
    )
    password = PasswordField(
        'Password',
        [DataRequired("Password field cannot be empty")]
    )
    submit = SubmitField('Submit')


class LoginForm(FlaskForm):
    username = StringField(
        'Username',
        [DataRequired("Username field cannot be empty")]
    )
    password = PasswordField(
        'Password',
        [DataRequired("Password field cannot be empty")]
    )
    submit = SubmitField('Login')


class ChangePasswordForm(FlaskForm):
    password = PasswordField(
        'Password',
        [DataRequired("ExPassword field cannot be empty")]
    )
    new_password = PasswordField(
        'New Password',
        [DataRequired("Password field cannot be empty")]
    )
    submit = SubmitField('Change')

app/modules/user/views.py
from app import db
from app.helpers.decorators import login_required
from app.models import User
from app.models.user_dict import UserDict
from app.modules.user.forms import ChangePasswordForm, LoginForm, RegisterForm
from flask import (Blueprint, flash, g, redirect, render_template, request,
                   session, url_for)

module = Blueprint('user', __name__, url_prefix='/user')


@module.route('/', methods=['GET'])
def index():
    return redirect(url_for('user.dashboard'))


@module.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm(request.form)
    if request.method == 'POST' and form.validate():
        user = User.query.filter(User.username == form.username.data).first()

        if user and user.check_password(form.password.data):
            session['user_id'] = user.id
            flash("You have logged successfully", 'success')
            return redirect(url_for('user.dashboard'))

        flash("Username or password is incorrect", 'error')
    return render_template('user/login.html', form=form)


@module.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm(request.form)
    if request.method == 'POST' and form.validate():
        user = User.query.filter(User.username == form.username.data).first()

        if user:
            flash("Username is already taken", 'error')
            return render_template('user/register.html', form=form)

        user = User(username=form.username.data)
        user.set_password(form.password.data)
        db.session.add(user)
        db.session.commit()
        flash("You have been successfully registered", 'success')
        return redirect(url_for('user.login'))

    return render_template('user/register.html', form=form)


@module.route('/logout', methods=['GET'])
@login_required
def logout():
    session.pop('user_id', None)
    flash('You have been logged out', 'success')
    return redirect(url_for('user.login'))


@module.route('/change-password', methods=['GET', 'POST'])
@login_required
def change_password():
    form = ChangePasswordForm(request.form)
    if request.method == 'POST' and form.validate():
        user = User.query.filter(User.username == g.user.username).first()

        if not user.check_password(form.password.data):
            flash("Please type last password correctly.")
            return render_template('user/change_password.html', form=form)

        user.set_password(form.new_password.data)
        db.session.commit()
        flash('Your password changed successfully')
        return redirect(url_for('user.dashboard'))

    return render_template('user/change_password.html', form=form)


@module.route('/dashboard', methods=['GET'])
@login_required
def dashboard():
    context = dict()
    context['words'] = UserDict.query.filter_by(user_id=g.user.id)
    return render_template('user/dashboard.html', content=context)

app/modules/word/views.py
import json
import random

import requests
from app import db
from app.helpers.decorators import login_required
from app.models import Synonym, UserDict, Word
from app.models.definition import Definition
from app.models.user import User
from flask import (Blueprint, g, redirect, render_template,
                   request, url_for)
from sqlalchemy.sql.expression import func
from config import configuration


module = Blueprint('word', __name__, url_prefix='/word')


@module.route('/search', methods=['GET', 'POST'])
@login_required
def search():
    context = dict()
    query = (request.args.get('search')).rstrip()
    user = g.user
    word = Word.query.filter_by(title=query).first()
    context['definitions'] = []

    if word:

        if not (user.words.filter_by(id=word.id).first()):
            user.words.append(word)
            db.session.add(user)
            db.session.commit()

        if not user.can_practice:
            if (user.words.count()) >= 10:
                user.can_practice = True

        context['definitions'] = Definition.query.filter_by(
            word_id=word.id
            ).all()
        user_dict = UserDict.query.filter_by(
            user_id=user.id,
            word_id=word.id).first()

        if not user_dict:
            user_dict = UserDict(
                user_id=user.id,
                word_id=word.id,
                search_count=1
            )
        else:
            user_dict.search_count += 1

        db.session.add(user_dict)
        db.session.commit()

    else:
        response = requests.request(
            'GET',
            f"{configuration.URL}{query}",
            headers=configuration.HEADERS
        )

        if response.status_code != 200:
            return render_template('user/index.html', content=context)

        items = json.loads(response.content)
        if response.status_code == 200 and items['results']:
            word = Word(title=query)
            db.session.add(word)
            db.session.commit()
            user.words.append(word)
            if not user.can_practice:
                if (user.words.count()) >= 10:
                    user.can_practice = True
            for item in items['results']:
                definition = Definition(
                    content=item['definition'],
                    word_id=word.id,
                    part_of_speech=item.get('partOfSpeech')
                )
                db.session.add(definition)
                db.session.commit()
                if item.get('synonyms'):
                    for synonym in item.get('synonyms'):
                        synonym = Synonym(title=synonym)
                        db.session.add(synonym)
                        definition.synonyms.append(synonym)

                db.session.add(user)
                db.session.add(definition)
                db.session.commit()
            user_dict = UserDict(
                user_id=user.id,
                word_id=word.id,
                search_count=1
            )

            db.session.add(user_dict)
            db.session.commit()

            context['definitions'] = Definition.query.filter_by(
                word_id=word.id
                ).all()

    return render_template('user/index.html', content=context)


@module.route('/details/<id>', methods=['GET'])
@login_required
def details(id):
    context = dict()
    word = Word.query.get(id)
    print(word)
    context['word'] = word
    return render_template('user/details.html', content=context)


@module.route('/practice', methods=['GET', 'POST'])
@login_required
def practice():
    context = dict()
    return render_template('user/practice.html', content=context)


@module.route('/practicing', methods=['GET'])
@login_required
def practicing():
    context = dict()
    user = User.query.get(g.user.id)
    three_words = user.words.order_by(func.random()).limit(3).all()
    querying_word = random.choice(three_words)
    user_dict = UserDict.query.filter_by(
        user_id=g.user.id,
        word_id=querying_word.id
        ).first()
    user_dict.appearance_count_update()
    querying_definition = Definition.query.filter_by(
        word_id=querying_word.id
        ).order_by(func.random()).first()

    context = json.dumps({
        'querying_definition': querying_definition.content,
        'first_word': three_words[0].title,
        'second_word': three_words[1].title,
        'third_word': three_words[2].title,
        })
    return context


@module.route('/check', methods=['POST'])
@login_required
def check():
    context = dict()
    if request.method == 'POST':
        querying_definition = request.form.get('querying_definition')
        answer = request.form.get('answer')

        definition_obj = Definition.query.filter_by(
            content=querying_definition
            ).first()
        exact_word = Word.query.get(definition_obj.word_id)
        user_dict_answer = UserDict.query.filter_by(
            user_id=g.user.id,
            word_id=exact_word.id
            ).first()
        user_dict_exact_answer = UserDict.query.filter_by(
            user_id=g.user.id,
            word_id=exact_word.id
            ).first()

        if exact_word.title == answer:
            user_dict_answer.practice_point += 1
            db.session.add(user_dict_answer)
            db.session.commit()

            context = json.dumps({
                'result': 'Contragulations. Your answer is correct',
                'definition': querying_definition,
                'word': exact_word.title,
            })
            return context

        else:
            words = request.form.getlist('words[]')
            words.remove(exact_word.title)
            user_dict_exact_answer.practice_point -= 2
            db.session.add(user_dict_exact_answer)
            db.session.commit()

            for item in words:
                word = Word.query.filter_by(title=item).first()
                user_dict_other = UserDict.query.filter_by(
                    user_id=g.user.id,
                    word_id=word.id
                ).first()
                user_dict_other.practice_point -= 1
                db.session.add(user_dict_other)
                db.session.commit()

            context = json.dumps({
                'result': 'Opps. Your answer is incorrect',
                'definition': querying_definition,
                'word': exact_word.title,
            })
            return context


@module.route('/exit-practice', methods=['GET'])
@login_required
def exit_practice():
    return redirect(url_for('word.practice'))

app/templates/user/change_password.html
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base/base.html" %}
{% set active_page = "register" %}
{% block content %}
    <div class="container">
        <div class="row justify-content-center">
        <div class="jumbotron">
            <h3 class="text-center">User Change Password</h3>
        </div>
        <div class="col-md-offset-4 col-md-4">
            {{ wtf.quick_form(form, button_map={'submit': 'success'}) }}
        </div>
    </div></div>
{%endblock %}

app/templates/user/dashboard.html
{% extends "base/base.html" %}
{% block content %}

<h2 class="text-center mt-2">User Dashboard</h2>
{% if not g.user.can_practice %}
  <h5 class="text-center mt-2">Please add at least 10 words to your dictionary by searching. Then "Practice" will be available.</h5>
{% endif %}

<table class="table table-striped mt-2">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Word Title</th>
            <th scope="col">Search Count</th>
            <th scope="col">Practicing Point</th>
            <th scope="col">Appearance Count</th>

        </tr>
    </thead>
    <tbody>
        {% for item in content.words %}
        <tr>
            <th class="col-1" scope="row">{{loop.index}}</th>
            <td class="col-5">
                <a href="{{  url_for('word.details', id=item.id) }}">
                    {{item.Word.title}}</a>
            </td>
            <td class="col-2">{{item.search_count}}</td>
            <td class="col-2">{{item.practice_point}}</td>
            <td class="col-2">{{item.appearance_count}}</td>
        </tr>
        {% endfor %}

    </tbody>
</table>





{%endblock %}

app/templates/user/details.html
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base/base.html" %}
{% block content %}

<h2 class="mt-2 text-center">{{ content.word.title }}</h2>

<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Definition</th>
            <th scope="col">Part of Speech</th>
            <th scope="col">Synonyms</th>
        </tr>
    </thead>
    <tbody>
        {% for item in content.word.definitions %}

        <tr>
            <th class="col-1" scope="row">{{loop.index}}</th>
            <td class="col-6">{{item.content}}</td>
            <td class="col-2">{{item.part_of_speech}}</td>
            <td class="col-3">
                {% for i in item.synonyms %}
                *{{i.title}} <br>

                {% endfor %}
            </td>

        </tr>
        {% endfor %}

    </tbody>
</table>




{%endblock %}

app/templates/user/index.html
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base/base.html" %}
{% set active_page = "register" %}
{% block content %}




{% include "base/components/result_table.html" %}







{%endblock %}

app/templates/user/login.html
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base/base.html" %}
{% set active_page = "register" %}
{% block content %}
    <div class="container">
        <div class="row justify-content-center">
        <div class="jumbotron">
            <h3 class="text-center">User Login</h3>
        </div>
        <div class="col-md-offset-4 col-md-4">
            {{ wtf.quick_form(form, button_map={'submit': 'success'}) }}
        </div>
    </div></div>
{%endblock %}

app/templates/user/practice.html
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base/base.html" %}
{% set active_page = "register" %}
{% block content %}

<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
  aria-labelledby="staticBackdropLabel" aria-hidden="true">

  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="result"></h5>
      </div>
      <div class="modal-body">
        <div class="row">
          <p>Definition : <span id="q_definition"></span></p>
        </div>
        <div class="row">
          <p>Answer : "<span id="exact_word"></span>"</p>
        </div>

      </div>
      <div class="modal-footer">
        <button type="button" id="continue" class="btn btn-secondary" data-bs-dismiss="modal">Continue</button>

      </div>
    </div>
  </div>
</div>


<h3 class="text-center mt-3">Word Practice Page</h3>
<hr>


<div class="container mt-3">
  <h4><span class="font-weight-bold">Definition:</span> <span class="text-center" id="definition"></span>
  </h4>
  <hr>
  <div class="row justify-content-center">

    <div class="col-md-3">
      <button type="button" class="btn btn-success btn-lg" id="first">
      </button>
    </div>
    <div class="col-md-3">
      <button type="button" class="btn btn-success btn-lg" id="second">
      </button>
    </div>
    <div class="col-md-3">
      <button type="button" class="btn btn-success btn-lg" id="third">
      </button>
    </div>
  </div>
  <div class="row mt-3">
    <div class="d-flex justify-content-center">

      <a id="start" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Start Practicing</a>

    </div>
  </div>
  <div class="row mt-3">
    <div class="d-flex justify-content-center">

      <a href="{{ url_for('word.exit_practice' )}}" id="exit" class="btn btn-danger btn-md active" role="button"
        aria-pressed="true">Exit Practice</a>

    </div>
  </div>
</div>



<script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc="
  crossorigin="anonymous"></script>

<script>

  $(document).ready(function () {

    $('#exit, #first, #second, #third').hide();

  });

  $('#start, #continue').click(start_practice);
  function start_practice() {
    $("#start").hide();
    $('#exit, #first, #second, #third').show();
    $.ajax({
      url: '/word/practicing',
      type: 'GET',
      success: function (data) {
        $('#definition').text(data.querying_definition);
        $('#first').text(data.first_word);
        $('#second').text(data.second_word);
        $('#third').text(data.third_word);


      },
      dataType: 'json',
    });
  }


  $('#first, #second, #third').click(submit);

  function submit() {
    words = [$('#first').text(), $('#second').text(), $('#third').text()]
    $.ajax({
      url: '/word/check',
      type: 'POST',
      data: {
        "querying_definition": $('#definition').text(),
        "answer": $(this).text(),
        "words": words
      },

      success: function (data) {

        $('#result').text(data.result)
        $('#q_definition').text(data.definition)
        $('#exact_word').text(data.word)
        $('#staticBackdrop').modal('show');

      },
      dataType: 'json',
    });


  }

</script>

{%endblock %}

app/templates/user/register.html
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base/base.html" %}
{% set active_page = "register" %}
{% block content %}
    <div class="container">
        <div class="row justify-content-center">
        <div class="jumbotron">
            <h3 class="text-center">User Register</h3>
        </div>
        <div class="col-md-offset-4 col-md-4">
            {{ wtf.quick_form(form, button_map={'submit': 'success'}) }}
        </div>
    </div></div>
{%endblock %}